# Minimal dark
cursor #c8c8c8
cursor_text_color #141414
foreground #c8c8c8
background #141414
selection_foreground #141414
selection_background #3a3a3a
color0  #1c1c1c
color8  #3a3a3a
color1  #5c5c5c
color9  #5c5c5c
color2  #8a8a8a
color10 #c8c8c8
color3  #8a8a8a
color11 #c8c8c8
color4  #8a8a8a
color12 #c8c8c8
color5  #8a8a8a
color13 #c8c8c8
color6  #8a8a8a
color14 #c8c8c8
color7  #c8c8c8
color15 #f2f2f2
