# Cursor
cursor #e1e3e4
cursor_text_color #111415

# Main
foreground #e1e3e4
background #111415
selection_foreground #003641
selection_background #58d6f7

# Black
color0 #171a1b
color8 #272b2c

# Red (Error colors are usually preserved even in monochrome for functionality)
color1 #ffb4ab
color9 #f71b00

# Green -> Primary
color2 #58d6f7
color10 #007c9c

# Yellow -> Secondary
color3 #b2cad3
color11 #3d7d96

# Blue -> Tertiary
color4 #c0c4eb
color12 #2939cf

# Magenta -> Primary
color5 #58d6f7
color13 #007c9c

# Cyan -> Secondary
color6 #b2cad3
color14 #3d7d96

# White
color7 #e1e3e4
color15 #bfc8cb
