{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:

{
  options.ai-tools.enable = lib.mkEnableOption "ai-tools";
  options.agentConfig.enable = lib.mkEnableOption "shared Claude and Codex agent configuration";

  config = lib.mkMerge [
    (lib.mkIf config.ai-tools.enable {
      home.packages =
        let
          inherit (pkgs.stdenv.hostPlatform) system;
          codexWithGithubToken = pkgs.writeShellScriptBin "codex" ''
            if [ -z "''${GITHUB_PAT_TOKEN:-}" ]; then
              export GITHUB_PAT_TOKEN="$(${lib.getExe pkgs.gh} auth token)"
            fi

            exec ${lib.getExe pkgs.codex} "$@"
          '';
        in
        (with pkgs; [
          opencode
          mcp-nixos
          poppler-utils
          pandoc
          file
          sox
          rtk
        ])
        ++ [
          codexWithGithubToken
          inputs.claude-code-nix.packages.${system}.claude-code
          inputs.nix-agent.packages.${system}.default
          inputs.terax.packages.${system}.default
        ];

      xdg.configFile."rtk/config.toml".text = ''
        # RTK config. Partial - unspecified sections use built-in defaults.

        [hooks]
        exclude_commands = ["git diff", "git status", "rg"]

        [telemetry]
        enabled = false
      '';
    })

    (lib.mkIf config.agentConfig.enable (
      let
        syncClaudeCodexConfig = pkgs.writeShellApplication {
          name = "sync-claude-codex-config";
          runtimeInputs = with pkgs; [
            coreutils
            findutils
            gawk
            jq
          ];
          text = ''
            set -eu

            claude_dir="${config.home.homeDirectory}/.claude"
            claude_skills="$claude_dir/skills"
            claude_instructions="$claude_dir/CLAUDE.md"
            claude_settings="$claude_dir/settings.json"
            claude_installed_plugins="$claude_dir/plugins/installed_plugins.json"
            codex_dir="${config.home.homeDirectory}/.codex"
            codex_skills="$codex_dir/skills"
            codex_instructions="$codex_dir/AGENTS.md"

            mkdir -p "$codex_dir" "$codex_skills"

            link_codex_skill() {
              source_path="$1"
              name="$2"

              case "$name" in
                .*|"")
                  return 0
                  ;;
              esac

              target="$codex_skills/$name"
              if [ -e "$target" ] && [ ! -L "$target" ]; then
                echo "Skipping $target because it is not a symlink" >&2
              else
                ln -sfn "$source_path" "$target"
              fi
            }

            if [ -d "$claude_skills" ]; then
              find "$claude_skills" -mindepth 1 -maxdepth 1 -print | while IFS= read -r skill; do
                link_codex_skill "$skill" "$(basename "$skill")"
              done
            fi

            if [ -f "$claude_settings" ] && [ -f "$claude_installed_plugins" ]; then
              jq -r '.enabledPlugins // {} | to_entries[] | select(.value == true) | .key' "$claude_settings" |
                while IFS= read -r plugin_key; do
                  plugin_name="''${plugin_key%@*}"
                  install_path="$(
                    jq -r --arg key "$plugin_key" '.plugins[$key][0].installPath // empty' "$claude_installed_plugins"
                  )"

                  if [ -z "$install_path" ] || [ ! -d "$install_path" ]; then
                    continue
                  fi

                  if [ -f "$install_path/SKILL.md" ]; then
                    link_codex_skill "$install_path" "$plugin_name"
                  fi

                  for skills_dir in "$install_path/skills" "$install_path/.claude/skills"; do
                    if [ -d "$skills_dir" ]; then
                      find "$skills_dir" -mindepth 1 -maxdepth 1 -type d -print |
                        while IFS= read -r skill; do
                          if [ -f "$skill/SKILL.md" ]; then
                            link_codex_skill "$skill" "$(basename "$skill")"
                          fi
                        done
                    fi
                  done
                done
            fi

            if [ -f "$claude_instructions" ]; then
              {
                echo "# AGENTS.md"
                echo
                echo "Generated by Home Manager from $claude_instructions."
                echo "Edit the Claude file, then wait for the sync timer or run sync-claude-codex-config."
                echo
                awk '
                  $0 == "# Delegating to codex" { skip = 1; next }
                  skip && /^# / { skip = 0 }
                  !skip { print }
                ' "$claude_instructions"
              } > "$codex_instructions"
            fi
          '';
        };
      in
      {
        home.packages = [ syncClaudeCodexConfig ];

        home.activation.syncClaudeCodexConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          ${lib.getExe syncClaudeCodexConfig}
        '';

        systemd.user.services.sync-claude-codex-config = {
          Unit = {
            Description = "Sync Claude agent config into Codex";
          };
          Service = {
            Type = "oneshot";
            ExecStart = lib.getExe syncClaudeCodexConfig;
          };
        };

        systemd.user.timers.sync-claude-codex-config = {
          Unit = {
            Description = "Periodically sync Claude agent config into Codex";
          };
          Timer = {
            OnBootSec = "2m";
            OnUnitActiveSec = "5m";
            Unit = "sync-claude-codex-config.service";
          };
          Install = {
            WantedBy = [ "timers.target" ];
          };
        };
      }
    ))
  ];
}
