{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:

{
  options.ai-tools.enable = lib.mkEnableOption "ai-tools";
  options.agentConfig.enable = lib.mkEnableOption "shared Claude and Codex agent configuration";

  config = lib.mkMerge [
    (lib.mkIf config.ai-tools.enable {
      home.packages =
        let
          system = pkgs.stdenv.hostPlatform.system;
        in
        (with pkgs; [
          opencode
          codex
          mcp-nixos
        ])
        ++ [
          inputs.claude-code-nix.packages.${system}.claude-code
          inputs.nix-agent.packages.${system}.default
          inputs.terax.packages.${system}.default
        ];
    })

    (lib.mkIf config.agentConfig.enable (
      let
        syncClaudeCodexConfig = pkgs.writeShellApplication {
          name = "sync-claude-codex-config";
          runtimeInputs = with pkgs; [
            coreutils
            findutils
          ];
          text = ''
            set -eu

            claude_dir="${config.home.homeDirectory}/.claude"
            claude_skills="$claude_dir/skills"
            claude_instructions="$claude_dir/CLAUDE.md"
            codex_dir="${config.home.homeDirectory}/.codex"
            codex_skills="$codex_dir/skills"
            codex_instructions="$codex_dir/AGENTS.md"

            mkdir -p "$codex_dir" "$codex_skills"

            if [ -d "$claude_skills" ]; then
              find "$claude_skills" -mindepth 1 -maxdepth 1 -print | while IFS= read -r skill; do
                name="$(basename "$skill")"

                case "$name" in
                  .*|"")
                    continue
                    ;;
                esac

                target="$codex_skills/$name"
                if [ -e "$target" ] && [ ! -L "$target" ]; then
                  echo "Skipping $target because it is not a symlink" >&2
                else
                  ln -sfn "$skill" "$target"
                fi
              done
            fi

            if [ -f "$claude_instructions" ]; then
              {
                echo "# AGENTS.md"
                echo
                echo "Generated by Home Manager from $claude_instructions."
                echo "Edit the Claude file, then wait for the sync timer or run sync-claude-codex-config."
                echo
                cat "$claude_instructions"
              } > "$codex_instructions"
            fi
          '';
        };
      in
      {
        home.packages = [ syncClaudeCodexConfig ];

        home.activation.syncClaudeCodexConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          ${lib.getExe syncClaudeCodexConfig}
        '';

        systemd.user.services.sync-claude-codex-config = {
          Unit = {
            Description = "Sync Claude agent config into Codex";
          };
          Service = {
            Type = "oneshot";
            ExecStart = lib.getExe syncClaudeCodexConfig;
          };
        };

        systemd.user.timers.sync-claude-codex-config = {
          Unit = {
            Description = "Periodically sync Claude agent config into Codex";
          };
          Timer = {
            OnBootSec = "2m";
            OnUnitActiveSec = "5m";
            Unit = "sync-claude-codex-config.service";
          };
          Install = {
            WantedBy = [ "timers.target" ];
          };
        };
      }
    ))
  ];
}
