{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:

{
  options.ai-tools.enable = lib.mkEnableOption "ai-tools";
  options.agentConfig.enable = lib.mkEnableOption "shared Claude and Codex agent configuration";

  config = lib.mkMerge [
    (lib.mkIf config.ai-tools.enable {
      home.packages =
        let
          system = pkgs.stdenv.hostPlatform.system;
        in
        (with pkgs; [
          opencode
          codex
          mcp-nixos
        ])
        ++ [
          inputs.claude-code-nix.packages.${system}.claude-code
          inputs.nix-agent.packages.${system}.default
          inputs.terax.packages.${system}.default
        ];
    })

    (lib.mkIf config.agentConfig.enable {
      home.activation.syncClaudeCodexConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        claude_dir="${config.home.homeDirectory}/.claude"
        claude_skills="$claude_dir/skills"
        claude_instructions="$claude_dir/CLAUDE.md"
        codex_dir="${config.home.homeDirectory}/.codex"
        codex_skills="$codex_dir/skills"
        codex_instructions="$codex_dir/AGENTS.md"

        mkdir -p "$codex_dir" "$codex_skills"

        if [ -d "$claude_skills" ]; then
          find "$claude_skills" -mindepth 1 -maxdepth 1 -print | while IFS= read -r skill; do
            name="$(basename "$skill")"

            case "$name" in
              .*|"")
                continue
                ;;
            esac

            target="$codex_skills/$name"
            if [ -e "$target" ] && [ ! -L "$target" ]; then
              echo "Skipping $target because it is not a symlink" >&2
            else
              ln -sfn "$skill" "$target"
            fi
          done
        fi

        if [ -f "$claude_instructions" ]; then
          {
            echo "# AGENTS.md"
            echo
            echo "Generated by Home Manager from $claude_instructions."
            echo "Edit the Claude file, then run home-manager or nixos-rebuild to refresh this bridge."
            echo
            cat "$claude_instructions"
          } > "$codex_instructions"
        fi
      '';
    })
  ];
}
